name: Run Java Tests

on:
  push:
    branches:
      - main

  jobs:
    test:
      run-on: ubuntu-latest

      steps:
        - uses: action/checkout@v4

        - uses: action/setup-java@v4
          with:
            distribution: tener.in
            java-version: 21

          run: mvn test